### ISSUE TITLE
"Class not registered" error

### ISSUE THREAD

**Issue by scelicli** [ThePacielloGroup/WebAccessibilityToolbar#100] opened 2015-10-30 22:17 UTC
I recently downloaded the WAT and found that many of the items result in the following error:

Class not registered, ClassID: {00000000-0000-0000-0000-000000000000}

I'm using IE 11, Window 7, 64-bit OS.

Any ideas on why I would be receiving this error?

Sofia

**Comment by matatk** [comment] 2015-10-30 22:21
This is definitely not expected behaviour; there are a few things we can check to start with...

1. Was IE closed during installation?

2. Did you choose to enable add-ons when IE was first re-opened after installation? (I notification pop-up should've appeared at the bottom of the IE window asking about this)

3. Did you use the 64-bit installer for WAT?

**Comment by scelicli** [comment] 2015-10-30 22:36
Thank you for the quick response, Matthew.

1. Initially, IE was not closed. I received an error about that so I then
closed IE and restarted the WAT installation.

2. Yes, the pop up appeared at the bottom of the IE window and I chose to
enable.

3. Yes, I used the 64-bit installer (WAT_2015-05-20_32.64bit).

**Comment by matatk** [comment] 2015-10-30 22:38
No worries; I just happened to notice the report come in. Unfortunately I'm not 100% sure what might cause this. I have some ideas, but I wonder if @jun325 or @menovak (who do most of the development work on WAT) have seen this before? We will look into it as soon as we are able.

**Comment by menovak** [comment] 2015-11-03 14:15
hi Sofia,

As Matt replied, this is not an error we've seen before.  It almost sounds
like for some weird
reason, that WAT did not install properly.  Could you try something and
report back for me?

Can you go to the Tools :: Internet Options :: Programs :: Manage add-ons.
In that dialog, WAT should be listed with status of enabled.  If you double
click your mouse on the line which includes WAT, a more information dialog
should appear.  Could you take a screen shot of the 'more information'
dialog and send it to me?

Thanks

Mark

**Comment by scelicli** [comment] 2015-11-04 02:07
Hi Mark,

Here is the screen shot:
[image: Inline image 1]

I tried uninstalling and reinstalling but had the same result.

Sofia

**Comment by menovak** [comment] 2015-11-04 13:48
hi Sofia,

The image did not attach or did not email through, can you try again?

Thanks

Mark

**Comment by scelicli** [comment] 2015-11-04 19:00
![wat info](https://cloud.githubusercontent.com/assets/15479323/10948575/17b60bde-82e3-11e5-895b-68459f743b9c.jpg)
Sorry about that, Mark. I should have checked that the email paste would work here. Hopefully, you can see the attachment to this message.

**Comment by menovak** [comment] 2015-11-04 19:33
hi Sofia

Thanks, that time the image came through.   Looking at the results it
'appears' as though things are correct.

Question, when you installed WAT, did you do so with admin rights?  The
error message you are getting seems to indicate that the DLL (either the 32
or 64 bit) is/are not registered, which might happen if you do not have
proper privileges.

If you could do a complete uninstall (use the control panel 'Programs and
Features'), then reboot, then attempt a re-install after logging in with
admin rights (or change to admin rights), perhaps that will help?

If you have already done the installation process using admin rights, then
try to individually register the DLL files.  They are located in the
Web-Accessibility-Toolbar directory, each under Program Files and Program
Files (x86).  You may have to use the correct (32 bit versus 64 bit)
version of Regsvr32/64 with each DLL.  This Microsoft link ought to
help...you may have to reboot again once verifying based on the feedback
from Regsvr, once the DLLs are registered.

Let me know if this helps...

https://support.microsoft.com/en-us/kb/249873

Regards,

Mark




Regards,

Mark

**Comment by scelicli** [comment] 2015-11-04 21:12
Thanks, Mark.
Yes, I have Administrator status and have installed other software without issue.

I attempted to register the dll files but get an error (image of error message attached).

Sofia
![wat regsvr error](https://cloud.githubusercontent.com/assets/15479323/10952041/971daa32-82f5-11e5-912c-da87a3ab1ed0.jpg)

**Comment by menovak** [comment] 2015-11-04 21:37
Hi Sofia

My bad, I should have said to ONLY try to manually register the
accessibility_toolbar.dll, for both 32 and 64 bit.

Regards,

Mark

**Comment by scelicli** [comment] 2015-11-04 22:18
I still get errors.
Any other ideas?
![wat regsvr error ii](https://cloud.githubusercontent.com/assets/15479323/10953829/f02dddd2-82fe-11e5-9c67-447cc733ffc4.jpg)

**Comment by scelicli** [comment] 2015-11-04 22:41
I managed to get the Accessibility_Toolbar.dll files registered (seemingly) and rebooted but still encounter the same error when trying to use the WAT. 
Other ideas?

Thanks,
Sofia

**Comment by scelicli** [comment] 2015-11-04 23:08
In searching through possible reasons for the error(s), the possibility came up of having compiled the file in debug mode. This is suggested in the error message I posted 3 messages ago with the "side-by-side" reference. Can you please check that the files were compiled correctly.

Thanks,
Sofia

**Comment by menovak** [comment] 2015-11-04 23:42
hi Sofia,

When you downloaded the file from github, did you download the EXE
version?  If so, that would not have needed any compiling, and is the exact
same file I am running on Windows 8.1, without any issues.

I am puzzled at the moment and have no other good ideas..

Regards,

Mark

**Comment by matatk** [comment] 2015-11-05 10:55
I think we should probably try downloading a VM of this version of IE and Windows from https://dev.windows.com/en-us/microsoft-edge/tools/vms/ and see if we can reproduce it.  I will try this and get back to you.

Also @jun325: do you think this problem could be caused by the way in which the DLL is compiled? Is there an alternative we could try, just to see if that fixes the problem?

**Comment by jun325** [comment] 2015-11-05 15:57
I'm investigating the cause, but the cause of the error is still unknown.

@matatk
https://cloud.githubusercontent.com/assets/15479323/10952041/971daa32-82f5-11e5-912c-da87a3ab1ed0.jpg
The Resouces.dll doesn't need registering. Therefore, this error occurs inevitably.
I think the compiled method is not the issue.

@scelicli
Can you get the following value by using regedit?
HKEY_CLASSES_ROOT\CLSID\ {00000000-0000-0000-0000-000000000000}

**Comment by menovak** [comment] 2015-11-05 16:34
Thanks Jun

I had replied to Sofia, and explained that the Resources.dll was NOT the
dll to attempt to register, so that was my poor explanation, not Matt's,
but I think we cleared that up.

Mark

**Comment by scelicli** [comment] 2015-11-05 17:50
Thank you, all, for helping. I'm not that familiar with registering dll files, etc so the misunderstandings mostly fall on me.
Yes, I downloaded the exe file.
I opened the Registry Editor to look for HKEY_CLASSES_ROOT\CLSID\ {00000000-0000-0000-0000-000000000000} but I could not find a folder with that name. Am I looking in the right place?
![regedit](https://cloud.githubusercontent.com/assets/15479323/10976825/b331cd86-83a2-11e5-9a59-f966d174cc6d.jpg)

**Comment by jun325** [comment] 2015-11-05 23:43
Thank you Sofia.
You are looking at the right place. If the value exists, the system might be infected with some spywares.
following values exist?
WAT Script object
HKEY_CLASSES_ROOT\CLSID\ {4DC92CA7-D6CC-4FCD-95A5-BA85A58C4906} 
 IActiveScript
HKEY_CLASSES_ROOT\Interface\ {BB1A2AE1-A4F9-11CF-8F20-00805F2CD064}
These are necessary to execute the WAT script.

**Comment by scelicli** [comment] 2015-11-06 01:08
Thank you, Jun.
HKEY_CLASSES_ROOT\CLSID\ {4DC92CA7-D6CC-4FCD-95A5-BA85A58C4906} 
and
HKEY_CLASSES_ROOT\Interface\ {BB1A2AE1-A4F9-11CF-8F20-00805F2CD064}
exist.
![regedit ii](https://cloud.githubusercontent.com/assets/15479323/10986543/d4af3c86-83df-11e5-9b8c-9de5ea133989.jpg)
![regedit iii](https://cloud.githubusercontent.com/assets/15479323/10986548/da2a5718-83df-11e5-8b40-1b39b2951052.jpg)

**Comment by jun325** [comment] 2015-11-09 07:53
Thank you Sofia,

I think there is no problem with registration process.

Does the error occur in "Larger Images" function?
Are you using any security softwares(Antivirus and/or Antispyware)?

I plan to make other WAT for this problem. Please give me a little time.

**Comment by matatk** [comment] 2015-11-09 10:38
Thanks @jun325!

Just to update you on what I promised above: I can only get the 32-bit versions of Windows from modern.ie, so I could not test like-for-like, but @menovak was able to test with the 64-bit Windows 7 and was unable to reproduce the problem IIRC.

**Comment by scelicli** [comment] 2015-11-09 22:24
Hi Jun,

Yes, the problem occurs with the "Larger Images" function as well.
Yes, I am using Norton for security. I have tried disabling Norton and reinstalling WAT but the same result occurs.

Sofia

**Comment by jun325** [comment] 2015-11-24 02:45
Hi Sofia,

I have uploaded WAT installer.
1. uninstall existing WAT
2. install this(https://github.com/jun325/WebAccessibilityToolbar/blob/upstream/wat/WAT_2.1.1.27_32%2B64bit.exe) WAT
3. execute menu items(1 to 5)
![wat_21127](https://cloud.githubusercontent.com/assets/5038132/11356124/fbe0148e-929d-11e5-802e-3f5d18d25f1d.jpg)

Please let me know the results.

**Comment by scelicli** [comment] 2015-12-15 21:14
Sorry for the delay, Jun.

Here are the results (after needing to exclude the file from Norton's security auto-removal feature!):

Test 1: 0 alt errors out of 0 larger images with 0 images to review

Test 2: Class not registered, ClassID: {00000000-0000-0000-0000-000000000000}(Func1-6-ws:scripts/alert.ws)

Test 3: Class not registered, ClassID: {00000000-0000-0000-0000-000000000000}(Func1-6-ws:scripts/document.ws)

Test 4: Class not registered, ClassID: {00000000-0000-0000-0000-000000000000}(Func1-6-ws:scripts/localize.ws)

Test 5: Class not registered, ClassID: {00000000-0000-0000-0000-000000000000}(Func1-6-ws:scripts/AltInLargerImage.ws)

**Comment by jun325** [comment] 2016-01-10 09:42
Thanks sofia.

Could you execute the following command after closing IE?
regsvr32 jscript.dll

**Comment by scelicli** [comment] 2016-01-12 23:59
Hi Jun,
Here is the result:
![jscript_result](https://cloud.githubusercontent.com/assets/15479323/12280780/766303ec-b945-11e5-80f5-a57fed0122b8.jpg)

**Comment by jun325** [comment] 2016-01-19 05:16
Hi sofia,

The regsvr32 needs the administrative privileges.

**Comment by scelicli** [comment] 2016-03-23 02:43
Thanks, Jun.

I have executed 'regsvr32 jscript.dll' with administration privileges and got a message that it was successful. I installed the toolbar and tried one of the functions: list of images and received an error of class not registered again.
![wat error mar2016](https://cloud.githubusercontent.com/assets/15479323/13974110/3de54b94-f066-11e5-9e30-7b6b25a17f96.jpg)

**Comment by jun325** [comment] 2016-04-26 03:34
Hi sofia,

Please execute the following commands with the administration privileges.

cd c:\windows\syswow64
regsvr32 jscript.dll

**Comment by scelicli** [comment] 2016-04-26 17:57
Hi Jun,

That worked! 
Thank you for all of your time and patience.

Sofia

**Closed** 2016-04-26 19:11 UTC
Labels: bug
